name: pymodsecurity

dependencies:
  - python={{ os.environ.get('CONDA_PY', '3.7') }}
  - modsecurity={{ os.environ.get('MODSECURITY_VERSION', '3.0.3') }}
  - pybind11=2.5.0
  - pytest
  - pytest-mock

environment:
  PYTHONPATH:
    - {{ root }}
  LD_LIBRARY_PATH:
    - $CONDA_PREFIX/lib