name: pymodsecurity

dependencies:
  - python={{ os.environ.get('CONDA_PY', '3.6') }}
  - modsecurity={{ os.environ.get('MODSECURITY_VERSION', '3.0.2') }}
  - pybind11=2.2.3
  - pytest
  - pytest-mock
  - gcc

environment:
  PYTHONPATH:
    - {{ root }}
  LD_LIBRARY_PATH:
    - $CONDA_PREFIX/lib