{% set name = "pymodsecurity" %}
{% set version = "0.1" %}
{% set build_number = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: {{ build_number }}
  skip: true # [not linux]
  script_env:
    - CC
    - CXX

source:
  git_url: ../

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # - gcc
    - python
    - setuptools
    - pybind11
    - git
  host:
    - modsecurity
    - python
    - pybind11
  run:
    - modsecurity
    - python

test:
  imports:
    - ModSecurity
  commands:
    - python -c "from ModSecurity import ModSecurity"

about:
  summary: Python bindings to libmodsecurity
license_file: LICENSE.txt