stages:
  - build

image: ubuntu:bionic

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - bash .ci-support/setup.sh
  - bash .ci-support/install-conda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - bash .ci-support/install-modsecurity.sh
  - source activate pymodsecurity

##############################
#   Base Jobs definition
##############################
.build-base: &build-base
  stage: build
  script:
    - pip install .
    - py.test tests

##############################
#   Jobs definition
##############################
build:stable:
  <<: *build-base
  environment: stable
  only:
    - stable

build:release:
  <<: *build-base
  environment: release
  only:
    - /^release-.*$/

build:develop:
  <<: *build-base
  environment: develop
  only:
    - master
    - /^feature-.*$/
    - /^hotfix-.*$/
    - /^support-.*$/
