stages:
  - build

image: conda/miniconda3

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - bash .ci-support/setup.sh
  - conda config --add channels conda-forge
  - conda install conda-build pytest

##############################
#   Base Jobs definition
##############################
.build-base: &build-base
  stage: build
  script:
    - conda build recipe
    - conda install pymodsecurity -c local
    - py.test tests

##############################
#   Jobs definition
##############################
build:stable:
  <<: *build-base
  environment: stable
  only:
    - stable

build:release:
  <<: *build-base
  environment: release
  only:
    - /^release-.*$/

build:develop:
  <<: *build-base
  environment: develop
  only:
    - master
    - /^feature-.*$/
    - /^hotfix-.*$/
    - /^support-.*$/
